spring.datasource.url=jdbc:h2:mem:medicard_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

jwt.secret=medicard_jwt_secret_key_256bit_______________________________________
jwt.expiry=86400000

aes.secret=0123456789abcdef0123456789abcdef

server.port=8080

spring.sql.init.mode=never
# spring.sql.init.schema-locations=classpath:schema.sql
# spring.sql.init.data-locations=classpath:data.sql
